window.DISCIPLINAS_PPGEF = [
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "VILDE GOMES DE MENEZES",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "ATIVIDADES MOTORAS E GERONTOLOGIA",
    "nome_disciplina_completo": "ATIVIDADES MOTORAS E GERONTOLOGIA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "ANDRE LUIZ TORRES PIRAUA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "LUCIANO MACHADO FERREIRA TENORIO DE OLIVEIRA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "PEDRO PINHEIRO PAES NETO",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MEDIDAS E AVALIAÇÃO NO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "MEDIDAS E AVALIAÇÃO NO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "SAULO FERNANDES MELO DE OLIVEIRA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "BRENO QUINTELLA FARAH",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "VINICIUS DE OLIVEIRA DAMASCENO",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "ANDRE DOS SANTOS COSTA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "EDUARDO ZAPATERRA CAMPOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "BRENO QUINTELLA FARAH",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "RAFAEL DOS SANTOS HENRIQUE",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "FLAVIO RENATO BARROS DA GUARDA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "VILDE GOMES DE MENEZES",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "DANIEL DA ROCHA QUEIROZ",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "ANDRE LUIZ TORRES PIRAUA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Avaliação do desempenho motor em crianças e adolescentes",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Avaliação do desempenho motor em crianças e adolescentes)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "MATHEUS MAIA PACHECO",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1 - Avaliação do desempenho motor em crianças e adolescentes",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Avaliação do desempenho motor em crianças e adolescentes)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "RAFAEL DOS SANTOS HENRIQUE",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "41"
  },
  {
    "nome_turma": "1 - Avaliação e Prescrição de Treinamento Neuromuscular para Atletas de Alto Rendimento",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Avaliação e Prescrição de Treinamento Neuromuscular para Atletas de Alto Rendimento)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "FABIANO DE SOUZA FONSECA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 -  Fase I do projeto WSL judgement analysis",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 -  Fase I do projeto WSL judgement analysis)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "VILDE GOMES DE MENEZES",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "SAULO FERNANDES MELO DE OLIVEIRA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "BRENO QUINTELLA FARAH",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "BRENO QUINTELLA FARAH",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "ANDRE LUIZ TORRES PIRAUA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "FABIANO DE SOUZA FONSECA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1 -  Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 -  Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "FLAVIO RENATO BARROS DA GUARDA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 -  Fase I do projeto WSL judgement analysis",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 -  Fase I do projeto WSL judgement analysis)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "RAFAEL DOS SANTOS HENRIQUE",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "DANIEL DA ROCHA QUEIROZ",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "MOVIMENTO HUMANO E INTEGRAÇÃO METABÓLICA",
    "nome_disciplina_completo": "MOVIMENTO HUMANO E INTEGRAÇÃO METABÓLICA (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "ANDRE DOS SANTOS COSTA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "ANDRE LUIZ TORRES PIRAUA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "FABIANO DE SOUZA FONSECA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1 - Ergoespirometria",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Ergoespirometria)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "PEDRO PINHEIRO PAES NETO",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "ATIVIDADES MOTORAS E COGNIÇÃO",
    "nome_disciplina_completo": "ATIVIDADES MOTORAS E COGNIÇÃO (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "RAFAEL DOS SANTOS HENRIQUE",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "BRENO QUINTELLA FARAH",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "56"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "RAPHAEL MENDES RITTI DIAS",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "BRENO QUINTELLA FARAH",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "FABIANO DE SOUZA FONSECA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "ANDRE LUIZ TORRES PIRAUA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Biomecânica",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Biomecânica)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "MELISSA LEANDRO CELESTINO",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Paradesporto",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Paradesporto)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "SAULO FERNANDES MELO DE OLIVEIRA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "BILLY GRAEFF BASTOS",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CAROL VIRGINIA GOIS LEANDRO",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Gustavo Pascoal Paipe",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "MÁRIO TEIXEIRA",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "VILDE GOMES DE MENEZES",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "33"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "DANIEL DA ROCHA QUEIROZ",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "FABIANO DE SOUZA FONSECA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "ANDRE LUIZ TORRES PIRAUA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Revisão de Escopo",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 - Revisão de Escopo)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "LUCAS EDUARDO RODRIGUES DOS SANTOS",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1 - Revisão de Escopo",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 - Revisão de Escopo)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "OZEAS DE LIMA LINS FILHO",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "PAULO ROBERTO CAVALCANTI CARVALHO",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "SAULO FERNANDES MELO DE OLIVEIRA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA",
    "nome_disciplina_completo": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "DANIELA KARINA DA SILVA FERREIRA",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "37"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA",
    "nome_disciplina_completo": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "ILANA SANTOS DE OLIVEIRA",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA",
    "nome_disciplina_completo": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "FLAVIO RENATO BARROS DA GUARDA",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "ANDRE DOS SANTOS COSTA",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "MELISSA LEANDRO CELESTINO",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Metodologias ativas para aquisição de habilidades através dos jogos",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Metodologias ativas para aquisição de habilidades através dos jogos)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "JOSE MANUEL DELFA DE LA MORENA",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Metodologias ativas para aquisição de habilidades através dos jogos",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Metodologias ativas para aquisição de habilidades através dos jogos)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "PEDRO PINHEIRO PAES NETO",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "2 - Sono",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 2 - Sono)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "OZEAS DE LIMA LINS FILHO",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA",
    "nome_disciplina_completo": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "CARLA MENESES HARDMAN",
    "categoria_responsavel": "Docente(s) Descredenciado(s)",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA",
    "nome_disciplina_completo": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "RILDO DE SOUZA WANDERLEY JUNIOR",
    "categoria_responsavel": "Pós-Doc",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "EDUARDO ZAPATERRA CAMPOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "LUCAS EDUARDO RODRIGUES DOS SANTOS",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "TONY MEIRELES DOS SANTOS",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "LEONARDO GOMES DE OLIVEIRA LUZ",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "LUCAS EDUARDO RODRIGUES DOS SANTOS",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "OZEAS DE LIMA LINS FILHO",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "RAFAEL DOS SANTOS HENRIQUE",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Gestão de Políticas do Esporte, inovação tecnológica e social",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Gestão de Políticas do Esporte, inovação tecnológica e social)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "VILDE GOMES DE MENEZES",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "2 - Gestão de Políticas do Esporte, inovação tecnológica e social",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 2 - Gestão de Políticas do Esporte, inovação tecnológica e social)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "VILDE GOMES DE MENEZES",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  }
];
