window.DISCIPLINAS_PPGEF = [
  {
    "nome_turma": "01",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Aspectos Epistemológicos do Movimento Humano",
    "nome_disciplina_completo": "Aspectos Epistemológicos do Movimento Humano (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Billy Graeff Bastos",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carol Virginia Gois Leandro",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Gustavo Pascoal Paipe",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Mário Teixeira",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "3"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "ASPECTOS EPISTEMOLÓGICOS DO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "33"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "ATIVIDADES MOTORAS E COGNIÇÃO",
    "nome_disciplina_completo": "ATIVIDADES MOTORAS E COGNIÇÃO (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "ATIVIDADES MOTORAS E GERONTOLOGIA",
    "nome_disciplina_completo": "ATIVIDADES MOTORAS E GERONTOLOGIA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Andre Luiz Torres Piraua",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Docência no Ensino Superior",
    "nome_disciplina_completo": "Docência no Ensino Superior (Turma: 01)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Saulo Fernandes Melo de Oliveira",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Docência no Ensino Superior",
    "nome_disciplina_completo": "Docência no Ensino Superior (Turma: 01)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Daniel da Rocha Queiroz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Docência no Ensino Superior",
    "nome_disciplina_completo": "Docência no Ensino Superior (Turma: 01)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Luciano Machado Ferreira Tenorio de Oliveira",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Pedro Pinheiro Paes Neto",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Saulo Fernandes Melo de Oliveira",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Ozeas de Lima Lins Filho",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Paulo Roberto Cavalcanti Carvalho",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "DOCÊNCIA NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "DOCÊNCIA NO ENSINO SUPERIOR (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Obrigatória",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Saulo Fernandes Melo de Oliveira",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "03",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Elaboração de Projetos de Intenção de Pesquisa",
    "nome_disciplina_completo": "Elaboração de Projetos de Intenção de Pesquisa (Turma: 03)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "03",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Elaboração de Projetos de Intenção de Pesquisa",
    "nome_disciplina_completo": "Elaboração de Projetos de Intenção de Pesquisa (Turma: 03)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Lucas Eduardo Rodrigues dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA",
    "nome_disciplina_completo": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA",
    "nome_disciplina_completo": "EPIDEMIOLOGIA DA ATIVIDADE FÍSICA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Rildo de Souza Wanderley Junior",
    "categoria_responsavel": "Pós-Doc",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "ESTÁGIO DE DOCÊNCIA",
    "nome_disciplina_completo": "ESTÁGIO DE DOCÊNCIA (Turma: 1)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Eduardo Zapaterra Campos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Lucas Eduardo Rodrigues dos Santos",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "FATORES PERIFÉRICOS E CENTRAIS RELACIONADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "INOVAÇÃO EM PESQUISA APLICADA AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA",
    "nome_disciplina_completo": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Daniela Karina da Silva Ferreira",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "37"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA",
    "nome_disciplina_completo": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Ilana Santos de Oliveira",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA",
    "nome_disciplina_completo": "INTERVENÇÕES PARA MUDANÇAS NO ESTILO DE VIDA (Turma: 1)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MEDIDAS E AVALIAÇÃO NO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "MEDIDAS E AVALIAÇÃO NO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Saulo Fernandes Melo de Oliveira",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Medidas e Avaliação no Desempenho Físico e Esportivo",
    "nome_disciplina_completo": "Medidas e Avaliação no Desempenho Físico e Esportivo (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Fabio Yuzo Nakamura",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Medidas e Avaliação no Desempenho Físico e Esportivo",
    "nome_disciplina_completo": "Medidas e Avaliação no Desempenho Físico e Esportivo (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Métodos e Técnicas de Pesquisa Aplicados ao Movimento Humano",
    "nome_disciplina_completo": "Métodos e Técnicas de Pesquisa Aplicados ao Movimento Humano (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Paulo Roberto Cavalcanti Carvalho",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Métodos e Técnicas de Pesquisa Aplicados ao Movimento Humano",
    "nome_disciplina_completo": "Métodos e Técnicas de Pesquisa Aplicados ao Movimento Humano (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Paulo Roberto Cavalcanti Carvalho",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Breno Quintella Farah",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Vinicius de Oliveira Damasceno",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Breno Quintella Farah",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Breno Quintella Farah",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "56"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Raphael Mendes Ritti Dias",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Flavio Renato Barros da Guarda",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS E TÉCNICAS DE PESQUISA APLICADOS AO MOVIMENTO HUMANO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Métodos Estatísticos Aplicados ao Movimento Humano",
    "nome_disciplina_completo": "Métodos Estatísticos Aplicados ao Movimento Humano (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Métodos Estatísticos Aplicados ao Movimento Humano",
    "nome_disciplina_completo": "Métodos Estatísticos Aplicados ao Movimento Humano (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Lucas Eduardo Rodrigues dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Métodos Estatísticos Aplicados ao Movimento Humano",
    "nome_disciplina_completo": "Métodos Estatísticos Aplicados ao Movimento Humano (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Daniel da Rocha Queiroz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Daniel da Rocha Queiroz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Daniel da Rocha Queiroz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "60"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Leonardo Gomes de Oliveira Luz",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Lucas Eduardo Rodrigues dos Santos",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Ozeas de Lima Lins Filho",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "5"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO",
    "nome_disciplina_completo": "MÉTODOS ESTATÍSTICOS APLICADOS AO MOVIMENTO HUMANO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "4",
    "carga_horaria_total": "60",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "MOVIMENTO HUMANO E INTEGRAÇÃO METABÓLICA",
    "nome_disciplina_completo": "MOVIMENTO HUMANO E INTEGRAÇÃO METABÓLICA (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "André dos Santos Costa",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "André dos Santos Costa",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "RECURSOS ERGOGÊNICOS APLICADOS AO DESEMPENHO ESPORTIVO (Turma: 1)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Eduardo Zapaterra Campos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Redação de Artigos Científicos",
    "nome_disciplina_completo": "Redação de Artigos Científicos (Turma: 01)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "João Carlos Bouzas Marins",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Redação de Artigos Científicos",
    "nome_disciplina_completo": "Redação de Artigos Científicos (Turma: 01)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Breno Quintella Farah",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Breno Quintella Farah",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "REDAÇÃO DE ARTIGOS CIENTÍFICOS",
    "nome_disciplina_completo": "REDAÇÃO DE ARTIGOS CIENTÍFICOS (Turma: 1)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Breno Quintella Farah",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Seminário de Projeto",
    "nome_disciplina_completo": "Seminário de Projeto (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Melissa Leandro Celestino",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Seminário de Projeto",
    "nome_disciplina_completo": "Seminário de Projeto (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Bruno Teixeira Barbosa",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Seminário de Projeto",
    "nome_disciplina_completo": "Seminário de Projeto (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "André dos Santos Costa",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Seminário de Projeto",
    "nome_disciplina_completo": "Seminário de Projeto (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Melissa Leandro Celestino",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Seminário de Projeto",
    "nome_disciplina_completo": "Seminário de Projeto (Turma: 01)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "André dos Santos Costa",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Andre Luiz Torres Piraua",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Andre Luiz Torres Piraua",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Fabiano de Souza Fonseca",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Andre Luiz Torres Piraua",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Fabiano de Souza Fonseca",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Fabiano de Souza Fonseca",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Fabiano de Souza Fonseca",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 1)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "André dos Santos Costa",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Andre Luiz Torres Piraua",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Andre Luiz Torres Piraua",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "2",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "SEMINÁRIO DE PROJETO",
    "nome_disciplina_completo": "SEMINÁRIO DE PROJETO (Turma: 2)",
    "nucleo_didatico": "01. Formação Científica de Base",
    "formacao_docente": "Não",
    "tipo": "Obrigatória",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Melissa Leandro Celestino",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 -  Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 -  Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Flavio Renato Barros da Guarda",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Avaliação do desempenho motor em crianças e adolescentes",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Avaliação do desempenho motor em crianças e adolescentes)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Matheus Maia Pacheco",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "4"
  },
  {
    "nome_turma": "1 - Avaliação do desempenho motor em crianças e adolescentes",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Avaliação do desempenho motor em crianças e adolescentes)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "41"
  },
  {
    "nome_turma": "1 - Biomecânica",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Biomecânica)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Melissa Leandro Celestino",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Metodologias ativas para aquisição de habilidades através dos jogos",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Metodologias ativas para aquisição de habilidades através dos jogos)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Jose Manuel Delfa de La Morena",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Metodologias ativas para aquisição de habilidades através dos jogos",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Metodologias ativas para aquisição de habilidades através dos jogos)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Pedro Pinheiro Paes Neto",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Flavio Renato Barros da Guarda",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer",
    "ano_periodo": "2021_1",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 1 - Métodos de Avaliação de Políticas e Programas de Saúde, Esporte e Lazer)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  },
  {
    "nome_turma": "2 - Sono",
    "ano_periodo": "2024_1",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM ATIVIDADES MOTORAS E SAÚDE (Turma: 2 - Sono)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Ozeas de Lima Lins Filho",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: COMPORTAMENTO DE MOVIMENTO DA CRIANÇA E DO ADOLESCENTE",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: COMPORTAMENTO DE MOVIMENTO DA CRIANÇA E DO ADOLESCENTE (Turma: 01)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Leonardo Luz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: LETRAMENTO CORPORAL",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: LETRAMENTO CORPORAL (Turma: 01)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Leonardo Luz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: LETRAMENTO CORPORAL",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: LETRAMENTO CORPORAL (Turma: 01)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Rafael dos Santos Henrique",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.1",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: SONO E ATIVIDADE FÍSICA",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: SONO E ATIVIDADE FÍSICA (Turma: 01)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Ozeas de Lima Lins Filho",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "02",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: SONO E ATIVIDADE FÍSICA",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Atividades Motoras e Saúde: SONO E ATIVIDADE FÍSICA (Turma: 02)",
    "nucleo_didatico": "02. Atividades Motoras e Saúde",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Ozeas de Lima Lins Filho",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Avaliação e Prescrição de Treinamento Neuromuscular para Atletas de Alto Rendimento",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Avaliação e Prescrição de Treinamento Neuromuscular para Atletas de Alto Rendimento)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Fabiano de Souza Fonseca",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Ergoespirometria",
    "ano_periodo": "2022_2",
    "ano": "2022",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Ergoespirometria)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Pedro Pinheiro Paes Neto",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Gestão de Políticas do Esporte, inovação tecnológica e social",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Gestão de Políticas do Esporte, inovação tecnológica e social)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "1 - Paradesporto",
    "ano_periodo": "2023_1",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 1 - Paradesporto)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Saulo Fernandes Melo de Oliveira",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "2 - Gestão de Políticas do Esporte, inovação tecnológica e social",
    "ano_periodo": "2024_2",
    "ano": "2024",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM DESEMPENHO ESPORTIVO (Turma: 2 - Gestão de Políticas do Esporte, inovação tecnológica e social)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Vilde Gomes de Menezes",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: Análise de vídeo no desempenho do surfe",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: Análise de vídeo no desempenho do surfe (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: Análise de vídeo no desempenho do surfe",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: Análise de vídeo no desempenho do surfe (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Marilia Lacerda Barbosa Fragoso",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: Análise de vídeo no desempenho do surfe",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: Análise de vídeo no desempenho do surfe (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Louisi de Mello Tomasi Dalazen",
    "categoria_responsavel": "Participante Externo",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "10"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: ERGOESPIROMETRIA",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: ERGOESPIROMETRIA (Turma: 01)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Pedro Pinheiro Paes Neto",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "02",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: LIMIARES METABÓLICOS",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Desempenho Físico e Esportivo: LIMIARES METABÓLICOS (Turma: 02)",
    "nucleo_didatico": "03. Desempenho Físico e Esportivo",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Eduardo Zapaterra Campos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "45"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Didática do Ensino Superior: ESTRATÉGIAS E MÉTODOS DE PRÁTICA DOCENTE NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Didática do Ensino Superior: ESTRATÉGIAS E MÉTODOS DE PRÁTICA DOCENTE NO ENSINO SUPERIOR (Turma: 01)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Daniel da Rocha Queiroz",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "22"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2025.2",
    "ano": "2025",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Didática do Ensino Superior: ESTRATÉGIAS E MÉTODOS DE PRÁTICA DOCENTE NO ENSINO SUPERIOR",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Didática do Ensino Superior: ESTRATÉGIAS E MÉTODOS DE PRÁTICA DOCENTE NO ENSINO SUPERIOR (Turma: 01)",
    "nucleo_didatico": "05. Formação Docente",
    "formacao_docente": "Sim",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Carla Meneses Hardman",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "23"
  },
  {
    "nome_turma": "1 -  Fase I do projeto WSL judgement analysis",
    "ano_periodo": "2021_2",
    "ano": "2021",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 -  Fase I do projeto WSL judgement analysis)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 -  Fase I do projeto WSL judgement analysis",
    "ano_periodo": "2022_1",
    "ano": "2022",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 -  Fase I do projeto WSL judgement analysis)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "30"
  },
  {
    "nome_turma": "1 - Revisão de Escopo",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 - Revisão de Escopo)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Lucas Eduardo Rodrigues dos Santos",
    "categoria_responsavel": "Egresso",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "1 - Revisão de Escopo",
    "ano_periodo": "2023_2",
    "ano": "2023",
    "nome_disciplina": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS",
    "nome_disciplina_completo": "TÓPICOS ESPECIAIS: TEMAS EMERGENTES EM MÉTODOS DE PESQUISA E ANÁLISES DE DADOS (Turma: 1 - Revisão de Escopo)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "2",
    "carga_horaria_total": "30",
    "nome_responsavel": "Tony Meireles dos Santos",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "15"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Métodos de Pesquisa e Análises de Dados: PROCESSAMENTO E ANÁLISE DE DADOS",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Métodos de Pesquisa e Análises de Dados: PROCESSAMENTO E ANÁLISE DE DADOS (Turma: 01)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Melissa Leandro Celestino",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Sim",
    "carga_horaria_docente": "25"
  },
  {
    "nome_turma": "01",
    "ano_periodo": "2026.1",
    "ano": "2026",
    "nome_disciplina": "Tópicos Especiais: Temas Emergentes em Métodos de Pesquisa e Análises de Dados: PROCESSAMENTO E ANÁLISE DE DADOS",
    "nome_disciplina_completo": "Tópicos Especiais: Temas Emergentes em Métodos de Pesquisa e Análises de Dados: PROCESSAMENTO E ANÁLISE DE DADOS (Turma: 01)",
    "nucleo_didatico": "04. Aprofundamento Geral",
    "formacao_docente": "Não",
    "tipo": "Eletiva",
    "quantidade_creditos": "3",
    "carga_horaria_total": "45",
    "nome_responsavel": "Conrado Torres Laett",
    "categoria_responsavel": "Docente",
    "indicador_responsavel_principal": "Não",
    "carga_horaria_docente": "20"
  }
];
