window.ORIENTACOES_PPGEF = [
  {
    docente: "André dos Santos Costa",
    tcc_andamento: 0,
    tcc_concluidas: 121,
    ic_andamento: 10,
    ic_concluidas: 43,
    mestrado_andamento: 10,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 15,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 2,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 2,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 1,
    total_andamento_apcn: 10,
    total_concluidas_apcn: 17,
    total_concluidas_d: 15,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 17,
    total_mestrado_concluido: 15
  },
  {
    docente: "Bruno Teixeira Barbosa",
    tcc_andamento: 0,
    tcc_concluidas: 37,
    ic_andamento: 5,
    ic_concluidas: 4,
    mestrado_andamento: 2,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 0,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 2,
    total_concluidas_apcn: 0,
    total_concluidas_d: 0,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 0,
    total_mestrado_concluido: 0
  },
  {
    docente: "Clarice Maria de Lucena Martins",
    tcc_andamento: 0,
    tcc_concluidas: 6,
    ic_andamento: 0,
    ic_concluidas: 6,
    mestrado_andamento: 0,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 9,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 1,
    doutorado_andamento: 1,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 4,
    doutorado_concluidas: 4,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 0,
    total_concluidas_apcn: 9,
    total_concluidas_d: 13,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 9,
    total_mestrado_concluido: 13
  },
  {
    docente: "Daniel da Rocha Queiroz",
    tcc_andamento: 2,
    tcc_concluidas: 36,
    ic_andamento: 5,
    ic_concluidas: 6,
    mestrado_andamento: 4,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 5,
    doutorado_andamento_co: 1,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 1,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 5,
    total_concluidas_apcn: 5,
    total_concluidas_d: 5,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 5,
    total_mestrado_concluido: 5
  },
  {
    docente: "Daniela Karina da Silva Ferreira",
    tcc_andamento: 0,
    tcc_concluidas: 33,
    ic_andamento: 0,
    ic_concluidas: 14,
    mestrado_andamento: 1,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 4,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 1,
    total_concluidas_apcn: 4,
    total_concluidas_d: 4,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 4,
    total_mestrado_concluido: 4
  },
  {
    docente: "Eduardo Zapaterra Campos",
    tcc_andamento: 0,
    tcc_concluidas: 17,
    ic_andamento: 3,
    ic_concluidas: 11,
    mestrado_andamento: 6,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 8,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 1,
    doutorado_andamento: 1,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 6,
    total_concluidas_apcn: 8,
    total_concluidas_d: 8,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 8,
    total_mestrado_concluido: 8
  },
  {
    docente: "Guilherme Assunção Ferreira",
    tcc_andamento: 0,
    tcc_concluidas: 10,
    ic_andamento: 1,
    ic_concluidas: 7,
    mestrado_andamento: 0,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 5,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 0,
    total_concluidas_apcn: 5,
    total_concluidas_d: 5,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 5,
    total_mestrado_concluido: 5
  },
  {
    docente: "Leonardo Gomes de Oliveira Luz",
    tcc_andamento: 0,
    tcc_concluidas: 58,
    ic_andamento: 0,
    ic_concluidas: 3,
    mestrado_andamento: 3,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 2,
    doutorado_andamento_co: 1,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 1,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 4,
    total_concluidas_apcn: 2,
    total_concluidas_d: 2,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 2,
    total_mestrado_concluido: 2
  },
  {
    docente: "Melissa Leandro Celestino",
    tcc_andamento: 0,
    tcc_concluidas: 7,
    ic_andamento: 4,
    ic_concluidas: 8,
    mestrado_andamento: 3,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 0,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 3,
    total_concluidas_apcn: 0,
    total_concluidas_d: 0,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 0,
    total_mestrado_concluido: 0
  },
  {
    docente: "Ozeas de Lima Lins Filho",
    tcc_andamento: 0,
    tcc_concluidas: 42,
    ic_andamento: 2,
    ic_concluidas: 5,
    mestrado_andamento: 5,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 2,
    doutorado_andamento_co: 2,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 2,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 7,
    total_concluidas_apcn: 2,
    total_concluidas_d: 2,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 2,
    total_mestrado_concluido: 2
  },
  {
    docente: "Paulo Felipe Ribeiro Bandeira",
    tcc_andamento: 0,
    tcc_concluidas: 21,
    ic_andamento: 5,
    ic_concluidas: 17,
    mestrado_andamento: 6,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 23,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 4,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 4,
    posdoc_andamento: 3,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 6,
    total_concluidas_apcn: 27,
    total_concluidas_d: 23,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 27,
    total_mestrado_concluido: 23
  },
  {
    docente: "Paulo Roberto Cavalcanti Carvalho",
    tcc_andamento: 0,
    tcc_concluidas: 135,
    ic_andamento: 5,
    ic_concluidas: 55,
    mestrado_andamento: 7,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 30,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 2,
    doutorado_andamento: 2,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 2,
    doutorado_concluidas: 2,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 7,
    total_concluidas_apcn: 30,
    total_concluidas_d: 32,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 30,
    total_mestrado_concluido: 32
  },
  {
    docente: "Pedro Pinheiro Paes",
    tcc_andamento: 12,
    tcc_concluidas: 91,
    ic_andamento: 6,
    ic_concluidas: 26,
    mestrado_andamento: 8,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 7,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 8,
    total_concluidas_apcn: 7,
    total_concluidas_d: 7,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 7,
    total_mestrado_concluido: 7
  },
  {
    docente: "Rafael dos Santos Henrique",
    tcc_andamento: 0,
    tcc_concluidas: 42,
    ic_andamento: 0,
    ic_concluidas: 17,
    mestrado_andamento: 7,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 11,
    doutorado_andamento_co: 1,
    doutorado_andamento_principal: 4,
    doutorado_andamento: 5,
    doutorado_concluintes_2026: 2,
    doutorado_concluidas_co: 1,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 1,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 8,
    total_concluidas_apcn: 12,
    total_concluidas_d: 11,
    total_concluintes_2026_apcn: 2,
    total_geral_apcn: 14,
    total_mestrado_concluido: 11
  },
  {
    docente: "Saulo Fernandes Melo de Oliveira",
    tcc_andamento: 0,
    tcc_concluidas: 33,
    ic_andamento: 3,
    ic_concluidas: 6,
    mestrado_andamento: 5,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 1,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 5,
    total_concluidas_apcn: 1,
    total_concluidas_d: 1,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 1,
    total_mestrado_concluido: 1
  },
  {
    docente: "Tony Meireles dos Santos",
    tcc_andamento: 0,
    tcc_concluidas: 77,
    ic_andamento: 0,
    ic_concluidas: 32,
    mestrado_andamento: 4,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 28,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 2,
    doutorado_andamento: 2,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 3,
    doutorado_concluidas_principal: 2,
    doutorado_concluidas: 5,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 3,
    total_andamento_apcn: 4,
    total_concluidas_apcn: 31,
    total_concluidas_d: 30,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 31,
    total_mestrado_concluido: 30
  },
  {
    docente: "Vilde Gomes de Menezes",
    tcc_andamento: 0,
    tcc_concluidas: 28,
    ic_andamento: 0,
    ic_concluidas: 6,
    mestrado_andamento: 3,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 14,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 5,
    doutorado_andamento: 5,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 5,
    doutorado_concluidas: 5,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 3,
    total_concluidas_apcn: 14,
    total_concluidas_d: 19,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 14,
    total_mestrado_concluido: 19
  },
  {
    docente: "Lucas Eduardo Rodrigues dos Santos",
    tcc_andamento: 0,
    tcc_concluidas: 6,
    ic_andamento: 0,
    ic_concluidas: 0,
    mestrado_andamento: 2,
    mestrado_concluintes_2026: 0,
    mestrado_concluidas: 2,
    doutorado_andamento_co: 0,
    doutorado_andamento_principal: 0,
    doutorado_andamento: 0,
    doutorado_concluintes_2026: 0,
    doutorado_concluidas_co: 0,
    doutorado_concluidas_principal: 0,
    doutorado_concluidas: 0,
    posdoc_andamento: 0,
    posdoc_concluintes_2026: 0,
    posdoc_concluidas: 0,
    total_andamento_apcn: 2,
    total_concluidas_apcn: 2,
    total_concluidas_d: 2,
    total_concluintes_2026_apcn: 0,
    total_geral_apcn: 2,
    total_mestrado_concluido: 2
  }
];
